Repository dojot/dojot-microservice-sdk-js, pull requests merged in 2020-09, with the labels that each got.

#9 Separate READMEs
  README.md
  lib/configManager/README.md
  lib/kafka/README.md
  lib/logging/README.md
Labels: documentation

#10 Fix ConfigManager image
  docs/images/ConfigManagerFlow.drawio
  docs/images/ConfigManagerFlow.png
  lib/configManager/README.md
Labels: documentation

#11 Fix links in Table of Content
  README.md
Labels: documentation

#13 Update node.js version
  .github/workflows/microservice-sdk-js.yml
  .github/workflows/publish-npm-and-github-packages.yml
  .npmrc
  examples/configManager/Dockerfile
  examples/configManager/docker-compose.yml
  examples/configManager/index.js
  examples/consumer/Dockerfile
  examples/logging/Dockerfile
  examples/producer/Dockerfile
  package.json
Labels: enhancement

#14 Fixing ConfigManager - Type.parseLine()
  lib/configManager/parsers/Type.js
Labels: bug

#12 [feat] Add Health Check/Graceful Shutdown module
  .npmrc
  README.md
  examples/serviceStateManager/Dockerfile
  examples/serviceStateManager/README.md
  examples/serviceStateManager/app/healthcheck/Worker.js
  examples/serviceStateManager/app/index.js
  examples/serviceStateManager/docker-compose.yml
  examples/serviceStateManager/package.json
  index.js
  lib/serviceStateManager/Manager.js
  lib/serviceStateManager/README.md
  lib/serviceStateManager/Worker.js
  lib/serviceStateManager/index.js
  npm-shrinkwrap.json
  package.json
  test/unit/serviceStateManager/HealthCheckerWorker.test.js
  test/unit/serviceStateManager/ServiceStateManager.test.js
Labels: enhancement
